// Generates web/icons.js (inline SVG paths for brand logos and UI icons) so the site needs no icon CDN.
//   simple-icons (CC0)          brand logos, drawn in their brand colour
//   @mdi/js (Apache-2.0)        generic icons, plus logos simple-icons no longer ships (AWS, Azure, C#, Java, LinkedIn, GitHub)
// Brand names and logos belong to their owners. Usage:
//   npm pack simple-icons @mdi/js --pack-destination /tmp/ic && (cd /tmp/ic && for f in *.tgz; do mkdir -p ${f%.tgz} && tar xzf $f -C ${f%.tgz}; done)
//   node tools/build_icons.mjs /tmp/ic
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const base = process.argv[2];
const dir = (prefix) => path.join(base, fs.readdirSync(base).find((d) => d.startsWith(prefix) && !d.endsWith(".tgz")), "package");
const si = dir("simple-icons"), mdi = dir("mdi-js");
const siPath = (slug) => /d="([^"]+)"/.exec(fs.readFileSync(path.join(si, "icons", slug + ".svg"), "utf8"))[1];
const mdiSrc = fs.readFileSync(path.join(mdi, "mdi.js"), "utf8");
const mdiPath = (name) => new RegExp(`export var ${name} = "([^"]+)"`).exec(mdiSrc)?.[1] ?? (() => { throw new Error("no mdi icon " + name); })();

const out = {};
// brand logos: [key, source, colour]
for (const [key, slug, hex] of [
  ["docker", "docker", "#2496ED"], ["kubernetes", "kubernetes", "#326CE5"], ["postgresql", "postgresql", "#4169E1"], ["snowflake", "snowflake", "#29B5E8"],
  ["selenium", "selenium", "#43B02A"], ["jenkins", "jenkins", "#D24939"], ["postman", "postman", "#FF6C37"], ["python", "python", "#3776AB"],
  ["jira", "jira", "#0052CC"], ["terraform", "terraform", "#844FBA"], ["git", "git", "#F05032"], ["confluence", "confluence", "#0052CC"], ["java", "openjdk", "#ED8B00"], ["hitachi", "hitachi", "#E60027"],
]) out[key] = { d: siPath(slug), color: hex };
for (const [key, name, hex] of [
  ["aws", "mdiAws", "#FF9900"], ["azure", "mdiMicrosoftAzure", "#0078D4"], ["csharp", "mdiLanguageCsharp", "#9B4F96"],
  ["github", "mdiGithub", null], ["linkedin", "mdiLinkedin", "#0A66C2"],
  ["oracle", "mdiDatabase", "#F80000"], ["sqlserver", "mdiMicrosoftSqlServer", "#CC2927"], ["testng", "mdiCheckAll", "#E35A2B"],
]) {
  let d;
  try { d = mdiPath(name); } catch { d = mdiPath("mdiDatabaseOutline"); }
  out[key] = { d, color: hex };
}
// generic UI icons (colour comes from CSS)
for (const [key, name] of [
  ["leader", "mdiAccountStar"], ["strategy", "mdiSitemap"], ["governance", "mdiDatabaseCog"], ["cloud", "mdiCloudOutline"], ["lineage", "mdiChartLine"],
  ["perf", "mdiSpeedometer"], ["quality", "mdiCheckDecagram"], ["api", "mdiApi"], ["ai", "mdiRobotOutline"], ["pin", "mdiMapMarkerOutline"],
  ["mail", "mdiEmailOutline"], ["web", "mdiWeb"], ["shield", "mdiShieldCheckOutline"], ["briefcase", "mdiBriefcaseOutline"], ["tools", "mdiToolboxOutline"],
  ["supervisor", "mdiAccountSupervisorOutline"], ["dsearch", "mdiDatabaseSearchOutline"], ["shieldlock", "mdiShieldLockOutline"], ["clipcheck", "mdiClipboardCheckMultipleOutline"],
  ["robotx", "mdiRobotExcitedOutline"], ["cloudcheck", "mdiCloudCheckOutline"], ["folder", "mdiFolderStarOutline"], ["utc", "mdiShieldAirplaneOutline"],
  ["school", "mdiSchoolOutline"], ["cert", "mdiCertificateOutline"], ["trophy", "mdiTrophyAward"], ["medal", "mdiMedalOutline"], ["star", "mdiStarCircleOutline"],
  ["vm", "mdiServerNetworkOutline"], ["puzzle", "mdiPuzzleOutline"], ["summary", "mdiTextBoxOutline"],
  ["code", "mdiCodeBraces"], ["database", "mdiDatabaseOutline"], ["bug", "mdiBugOutline"], ["flask", "mdiTestTube"], ["building", "mdiDomain"],
]) out[key] = { d: mdiPath(name), color: null };

const file = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../web/icons.js");
fs.writeFileSync(file, "/* GENERATED by tools/build_icons.mjs: simple-icons (CC0) + Material Design Icons (Apache-2.0). Brand logos belong to their owners. */\nwindow.ICONS = " + JSON.stringify(out) + ";\n");
console.log(Object.keys(out).length, "icons ->", file);
