/* Site identity and author details, in one place. Leave `linkedin` empty to hide that link. */
window.SITE = {
  name: "SDET Interview Playground",
  tagline: "Python, JavaScript, TypeScript and SQL practice for SDET and QA engineers",
  author: {
    name: "Vijayanand Puppala",
    handle: "Vijay-puppala",
    role: "Quality Engineering Manager",
    kicker: "Quality Engineering · Data Governance · GenAI",
    summary: "14+ years leading Quality Engineering teams across enterprise, cloud, embedded, firmware, hardware and SaaS, driving test strategy, data governance validation and GenAI-enabled automation.",
    location: "Hyderabad, India",
    email: "Vijayanand.hyd@gmail.com",
    github: "https://github.com/Vijay-puppala",
    linkedin: "https://www.linkedin.com/in/vijayanand-puppala/",
    websites: [
      { label: "Portfolio", url: "https://vijayanand-puppala-data-portfolio.vercel.app/" },
      { label: "Portfolio (Lovable)", url: "https://vijayanand-puppala-data-portfolio.lovable.app/" },
    ],
    summaryTitle: "14+ years of QA leadership, built for governed and regulated data",
    summarySub: "From test strategy and release sign-off to data governance validation and GenAI-driven automation.",
    summaryPoints: [
      { icon: "supervisor", html: "Led QE teams across <b>Hitachi Vantara's Pentaho Platform</b>, <b>Oracle Fusion HCM Cloud</b> and physical security solutions." },
      { icon: "dsearch", html: "Validated <b>Data Discovery, Metadata Catalog, Data Quality, Lineage, Classification, Profiling and Optimization</b> on-prem, hybrid and cloud." },
      { icon: "shieldlock", html: "Deep grasp of governance: sensitive data identification, access control, compliance validation, audit reporting (<b>GDPR, HIPAA, CCPA</b>)." },
      { icon: "clipcheck", html: "Defines test strategies, plans releases, manages certifications and owns quality across the SDLC." },
      { icon: "robotx", html: "Hands-on functional, regression, E2E, API, performance, scalability, exploratory and data-validation testing." },
      { icon: "cloudcheck", html: "Proficient with <b>AWS, Azure, Docker, Kubernetes</b>, Oracle, PostgreSQL, Snowflake, HP ALM, Jira, Confluence and Jenkins." },
    ],
    career: [
      { company: "Hitachi Vantara India Pvt. Ltd.", icon: "hitachi", place: "Hyderabad, India", position: "Software Development Engineer Test Engineering Manager M3", dates: "Jan 2022 – Present", current: true },
      { company: "Oracle India Pvt. Ltd.", icon: "oracle", place: "Hyderabad, India", position: "Principal Quality Assurance Engineer", dates: "Jun 2018 – Jan 2022" },
      { company: "United Technologies Corporation", icon: "utc", place: "Hyderabad, India", position: "Senior Engineer", dates: "Jul 2011 – Jun 2018" },
    ],
    pillars: [
      { icon: "leader", title: "Quality Engineering Leadership", text: "Team direction, mentoring and release ownership." },
      { icon: "strategy", title: "Test Strategy, Planning & Execution", text: "End-to-end SDLC ownership from planning to sign-off." },
      { icon: "governance", title: "Data Governance & Data Management Testing", text: "Governed data validation across environments." },
      { icon: "cloud", title: "AWS, Azure, Docker & Kubernetes", text: "Cloud-native infrastructure and containerized testing." },
      { icon: "lineage", title: "Data Discovery, Metadata Catalog & Lineage", text: "Cataloging, lineage tracking and profiling at scale." },
      { icon: "perf", title: "Performance & Scalability Testing", text: "Load, volume and scalability validation." },
      { icon: "quality", title: "Data Quality & Compliance Validation", text: "Scoring, profiling and regulatory validation (GDPR, HIPAA, CCPA)." },
      { icon: "api", title: "REST API Testing & Automation", text: "Selenium, REST-driven and Postman-driven suites." },
      { icon: "ai", title: "Gen AI & Agentic AI", text: "Agentic engineering and AI-assisted QA practice." },
    ],
    toolGroups: [
      { title: "Cloud & containers", icon: "cloud", tools: [["AWS", "aws"], ["Azure", "azure"], ["Docker", "docker"], ["Kubernetes", "kubernetes"]] },
      { title: "Databases", icon: "database", tools: [["Oracle", "oracle"], ["SQL Server", "sqlserver"], ["PostgreSQL", "postgresql"], ["Snowflake", "snowflake"]] },
      { title: "Automation & CI", icon: "flask", tools: [["Selenium", "selenium"], ["TestNG", "testng"], ["Jenkins", "jenkins"], ["Postman", "postman"]] },
      { title: "Languages", icon: "code", tools: [["Python", "python"], ["Java", "java"], ["C#", "csharp"]] },
      { title: "Tracking & docs", icon: "bug", tools: [["HP ALM", "bug"], ["BugDB", "bug"], ["Jira", "jira"], ["Confluence", "confluence"]] },
      { title: "Virtualization", icon: "vm", tools: [["VMware vCenter", "vm"]] },
    ],
    education: { icon: "school", title: "Master of Technology, Electrical & Electronics Engineering", where: "VNR Vignana Jyothi Institute of Engineering & Technology (JNTU), 2012", detail: "77.93% · First Class with Distinction" },
    awards: [
      { icon: "medal", html: "Certificate and multiple <b>Titan Awards</b> across releases for extraordinary performance, from the Director, UTC." },
      { icon: "medal", html: "Certificate and <b>Stallion Award</b> for extraordinary performance, from the Director, UTC." },
      { icon: "leader", html: "<b>Customer Focus Award</b> for exemplary contribution to Oracle Fusion HCM Cloud." },
      { icon: "star", html: "<b>Platinum and Gold Awards</b> for successful Pentaho Platform rollouts across multiple clients, from the President, Pentaho (Hitachi Vantara)." },
    ],
    compliance: ["GDPR", "HIPAA", "CCPA"],
  },
  repo: "https://github.com/Vijay-puppala/interview-playground",
};
